import React from "react";

import {
  Card,
  CardBody,
  Content,
  DescriptionList,
  DescriptionListDescription,
  DescriptionListGroup,
  DescriptionListTerm,
  Drawer,
  DrawerActions,
  DrawerCloseButton,
  DrawerContent,
  DrawerContentBody,
  DrawerHead,
  DrawerPanelBody,
  DrawerPanelContent,
  InputGroup,
  InputGroupItem,
  Label,
  PageSection,
  SearchInput,
  Stack,
  StackItem,
  Title,
} from "@patternfly/react-core";
import {
  Table,
  Tbody,
  Td,
  Th,
  Thead,
  Tr,
} from "@patternfly/react-table";

import { DocumentMetadata } from "@app/components/DocumentMetadata";
import { Link } from "react-router-dom";
import { Paths } from "@app/Routes";
import { getSbomFilteredByAlgorithmUrl } from "@app/pages/sbom-list/helpers";

interface CryptographicAsset {
  id: string;
  algorithm: string;
  keyStrength?: number;
  libraryName: string;
  libraryVersion: string;
  discoverySource: string;
  fips140_3Compliant: boolean;
  risk: "Critical" | "High" | "Medium" | "Low";
  type: "Library Capability" | "Hard-coded Insecure Crypto";
  libraryCapabilities?: string[]; // Algorithms the library supports
  detectedUsage?: string[]; // Algorithms actually detected in code
  // CBOM-specific fields (from CycloneDX CBOM format)
  primitive?: string; // e.g., "hash", "signature", "pke", "drbg", "key-agree", "kdf"
  cryptoFunctions?: string[]; // e.g., ["digest"], ["sign", "verify"], ["encrypt", "decrypt"]
  occurrences?: Array<{
    location: string;
    line: number;
    context?: string;
  }>;
  // SBOMs that use this cryptographic asset
  sboms?: Array<{
    id: string;
    name: string;
  }>;
}

// Mock data based on ProdSec requirements and CycloneDX CBOM format
// 
// ProdSec Requirements Summary (from meeting notes):
// - CBOMs generated using Scanoss enterprise licenses (adheres to CycloneDX/SPDX spec)
// - Primary customer need: Understanding where hard-coded insecure cryptography is present
// - Minimum requirement: Discoverability of library/package support (name + version)
// - Ideal: Visibility into missing components (what library supports but isn't used)
// - Current focus: Visibility and inventory (no remediations yet)
// - Future: Migration tracking, policy-based admission control, Insights integration
//
// Real CBOM Integration Notes:
// - CBOM files (CycloneDX format) contain cryptographic-asset components with:
//   - name: algorithm name (e.g., "SHA-1", "RSA", "ECDSA-P256")
//   - cryptoProperties.assetType: "algorithm" or "related-crypto-material"
//   - cryptoProperties.algorithmProperties.primitive: "hash", "signature", "pke", "drbg", "key-agree", "kdf"
//   - cryptoProperties.algorithmProperties.parameterSetIdentifier: key size (e.g., "256", "2048", "160")
//   - cryptoProperties.algorithmProperties.cryptoFunctions: ["digest"], ["sign", "verify"], ["encrypt", "decrypt"]
//   - evidence.occurrences: array of file locations and line numbers where detected
//   - evidence.identity[].methods[].value: discovery source (e.g., "scanoss:ruleid,...")
//
// To integrate real CBOM data:
// 1. Parse CycloneDX CBOM JSON files (generated by Scanoss)
// 2. Map CBOM components to CryptographicAsset interface
// 3. Determine risk level based on algorithm (SHA-1, MD5, weak RSA = Critical/High)
// 4. Determine type: "Hard-coded Insecure Crypto" if detected in code (evidence.occurrences present),
//    "Library Capability" if from dependency analysis (library supports but may not be used)
// 5. Extract library info from associated SBOM dependencies
// 6. Check FIPS 140-3 compliance based on algorithm and key strength
// 7. Identify missing components: Compare libraryCapabilities vs detectedUsage to show
//    what the library supports but isn't being used (addresses "potential for inclusion" requirement)
//
const mockCryptographicAssets: CryptographicAsset[] = [
  {
    id: "1",
    algorithm: "SHA-1",
    keyStrength: 160,
    libraryName: "Go crypto/sha1",
    libraryVersion: "1.21",
    discoverySource: "Scanoss",
    fips140_3Compliant: false,
    risk: "Critical",
    type: "Hard-coded Insecure Crypto",
    primitive: "hash",
    cryptoFunctions: ["digest"],
    libraryCapabilities: ["SHA-256", "SHA-384", "SHA-512", "SHA-1"],
    detectedUsage: ["SHA-1"],
    occurrences: [
      {
        location: "pkg/asset/imagebased/configimage/ingressoperatorsigner.go",
        line: 172,
        context: "hash := sha1.Sum(publicKeyBytes)",
      },
      {
        location: "pkg/asset/tls/tls.go",
        line: 142,
        context: "hash := sha1.Sum(publicKeyBytes)",
      },
    ],
    sboms: [
      { id: "sbom-1", name: "openshift-installer-v4.15.0" },
      { id: "sbom-2", name: "openshift-installer-agent-v4.15.0" },
    ],
  },
  {
    id: "2",
    algorithm: "RSA",
    keyStrength: 2048,
    libraryName: "Go crypto/rsa",
    libraryVersion: "1.21",
    discoverySource: "Scanoss",
    fips140_3Compliant: true,
    risk: "Medium",
    type: "Hard-coded Insecure Crypto",
    primitive: "pke",
    cryptoFunctions: ["encrypt", "decrypt"],
    libraryCapabilities: ["RSA-2048", "RSA-4096", "ECDSA"],
    detectedUsage: ["RSA-2048"],
    occurrences: [
      {
        location: "internal/tshelpers/fakeregistry.go",
        line: 302,
        context: "pk, err := rsa.GenerateKey(rand.Reader, 2048)",
      },
      {
        location: "pkg/asset/tls/tls.go",
        line: 48,
        context: "rsaKey, err := rsa.GenerateKey(rand.Reader, keySize)",
      },
    ],
    sboms: [
      { id: "sbom-1", name: "openshift-installer-v4.15.0" },
    ],
  },
  {
    id: "3",
    algorithm: "AES-256",
    keyStrength: 256,
    libraryName: "OpenSSL",
    libraryVersion: "3.0.8",
    discoverySource: "Scanoss",
    fips140_3Compliant: true,
    risk: "Low",
    type: "Library Capability",
    libraryCapabilities: ["AES-128", "AES-192", "AES-256", "ChaCha20"],
  },
  {
    id: "4",
    algorithm: "CRYSTALS-Kyber",
    keyStrength: 768,
    libraryName: "liboqs",
    libraryVersion: "0.8.0",
    discoverySource: "Scanoss",
    fips140_3Compliant: false,
    risk: "Low",
    type: "Library Capability",
    libraryCapabilities: [
      "CRYSTALS-Kyber",
      "CRYSTALS-Dilithium",
      "FALCON",
      "SPHINCS+",
    ],
  },
  {
    id: "5",
    algorithm: "MD5",
    keyStrength: 128,
    libraryName: "Go crypto/md5",
    libraryVersion: "1.21",
    discoverySource: "Scanoss",
    fips140_3Compliant: false,
    risk: "Critical",
    type: "Hard-coded Insecure Crypto",
    primitive: "hash",
    cryptoFunctions: ["digest"],
    libraryCapabilities: ["SHA-256", "SHA-384", "SHA-512", "MD5"],
    detectedUsage: ["MD5"],
    occurrences: [
      {
        location: "pkg/types/gcp/clouduid.go",
        line: 11,
        context: "hash := md5.Sum([]byte(infraID))",
      },
    ],
    sboms: [
      { id: "sbom-1", name: "openshift-installer-v4.15.0" },
    ],
  },
  {
    id: "6",
    algorithm: "RSA",
    keyStrength: 2048,
    libraryName: "BoringSSL",
    libraryVersion: "1.1.1",
    discoverySource: "Scanoss",
    fips140_3Compliant: true,
    risk: "Medium",
    type: "Library Capability",
    libraryCapabilities: ["RSA-2048", "RSA-4096", "ECDSA"],
  },
  {
    id: "7",
    algorithm: "DES",
    keyStrength: 56,
    libraryName: "libcrypto",
    libraryVersion: "1.0.2",
    discoverySource: "Scanoss",
    fips140_3Compliant: false,
    risk: "Critical",
    type: "Hard-coded Insecure Crypto",
    libraryCapabilities: ["AES-256", "DES", "3DES"],
    detectedUsage: ["DES"],
  },
  {
    id: "8",
    algorithm: "ECDSA-P256",
    keyStrength: 256,
    libraryName: "Go crypto/ecdsa",
    libraryVersion: "1.21",
    discoverySource: "Scanoss",
    fips140_3Compliant: true,
    risk: "Low",
    type: "Hard-coded Insecure Crypto",
    primitive: "signature",
    cryptoFunctions: ["sign", "verify"],
    libraryCapabilities: ["ECDSA-P256", "ECDSA-P384", "ECDSA-P521"],
    detectedUsage: ["ECDSA-P256"],
    occurrences: [
      {
        location: "pkg/asset/agent/gencrypto/authconfig.go",
        line: 123,
        context: "priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)",
      },
    ],
    sboms: [
      { id: "sbom-2", name: "openshift-installer-agent-v4.15.0" },
    ],
  },
];

export const CBOMInventory: React.FC = () => {
  const [selectedAsset, setSelectedAsset] =
    React.useState<CryptographicAsset | null>(null);
  const [isDrawerOpen, setIsDrawerOpen] = React.useState(false);
  const [searchValue, setSearchValue] = React.useState("");

  const handleRowClick = (asset: CryptographicAsset) => {
    setSelectedAsset(asset);
    setIsDrawerOpen(true);
  };

  const onDrawerClose = () => {
    setIsDrawerOpen(false);
    setSelectedAsset(null);
  };

  // Filter assets based on search
  const filteredAssets = React.useMemo(() => {
    if (!searchValue.trim()) {
      return mockCryptographicAssets;
    }

    const searchLower = searchValue.toLowerCase();
    return mockCryptographicAssets.filter(
      (asset) =>
        asset.algorithm.toLowerCase().includes(searchLower) ||
        asset.libraryName.toLowerCase().includes(searchLower) ||
        asset.type.toLowerCase().includes(searchLower) ||
        asset.risk.toLowerCase().includes(searchLower),
    );
  }, [searchValue]);

  const getRiskColor = (risk: CryptographicAsset["risk"]) => {
    switch (risk) {
      case "Critical":
        return "red";
      case "High":
        return "orange";
      case "Medium":
        return "yellow";
      case "Low":
        return "green";
      default:
        return "grey";
    }
  };

  const getTypeColor = (type: CryptographicAsset["type"]) => {
    switch (type) {
      case "Hard-coded Insecure Crypto":
        return "red";
      case "Library Capability":
        return "blue";
      default:
        return "grey";
    }
  };

  const columns = ["Algorithm", "Library", "Type", "Risk", "SBOMs"];

  return (
    <>
      <DocumentMetadata title="Cryptography" />
      <PageSection variant="light">
        <Stack hasGutter>
          <StackItem>
            <Title headingLevel="h1" size="2xl">
              Cryptography
            </Title>
            <Content>
              Discover and inventory cryptographic assets across your software
              supply chain. Identify library capabilities, detect hard-coded
              insecure cryptographic usage, and understand what cryptographic
              components are available but not yet utilized.
            </Content>
          </StackItem>
          <StackItem>
            <InputGroup>
              <InputGroupItem isFill>
                <SearchInput
                  placeholder="Search by algorithm, library, type, or risk..."
                  value={searchValue}
                  onChange={(_, value) => setSearchValue(value)}
                  onClear={() => setSearchValue("")}
                />
              </InputGroupItem>
            </InputGroup>
          </StackItem>
        </Stack>
      </PageSection>
      <Drawer isExpanded={isDrawerOpen} isInline>
        <DrawerContent
          panelContent={
            <DrawerPanelContent>
              <DrawerHead>
                <Title headingLevel="h2" size="xl">
                  {selectedAsset?.algorithm || "Select an asset"}
                </Title>
                <DrawerActions>
                  <DrawerCloseButton onClose={onDrawerClose} />
                </DrawerActions>
              </DrawerHead>
              <DrawerPanelBody>
                {selectedAsset ? (
                  <Stack hasGutter>
                    <StackItem>
                      <Card>
                        <CardBody>
                          <DescriptionList>
                            <DescriptionListGroup>
                              <DescriptionListTerm>Algorithm</DescriptionListTerm>
                              <DescriptionListDescription>
                                {selectedAsset.algorithm}
                              </DescriptionListDescription>
                            </DescriptionListGroup>
                            {selectedAsset.keyStrength && (
                              <DescriptionListGroup>
                                <DescriptionListTerm>
                                  Key Strength
                                </DescriptionListTerm>
                                <DescriptionListDescription>
                                  {selectedAsset.keyStrength} bits
                                </DescriptionListDescription>
                              </DescriptionListGroup>
                            )}
                            <DescriptionListGroup>
                              <DescriptionListTerm>Library</DescriptionListTerm>
                              <DescriptionListDescription>
                                {selectedAsset.libraryName} v
                                {selectedAsset.libraryVersion}
                              </DescriptionListDescription>
                            </DescriptionListGroup>
                            <DescriptionListGroup>
                              <DescriptionListTerm>
                                Discovery Source
                              </DescriptionListTerm>
                              <DescriptionListDescription>
                                {selectedAsset.discoverySource}
                              </DescriptionListDescription>
                            </DescriptionListGroup>
                            <DescriptionListGroup>
                              <DescriptionListTerm>Type</DescriptionListTerm>
                              <DescriptionListDescription>
                                <Label color={getTypeColor(selectedAsset.type)}>
                                  {selectedAsset.type}
                                </Label>
                              </DescriptionListDescription>
                            </DescriptionListGroup>
                            <DescriptionListGroup>
                              <DescriptionListTerm>Risk</DescriptionListTerm>
                              <DescriptionListDescription>
                                <Label color={getRiskColor(selectedAsset.risk)}>
                                  {selectedAsset.risk}
                                </Label>
                              </DescriptionListDescription>
                            </DescriptionListGroup>
                            <DescriptionListGroup>
                              <DescriptionListTerm>
                                FIPS 140-3 Status
                              </DescriptionListTerm>
                              <DescriptionListDescription>
                                <Label
                                  color={
                                    selectedAsset.fips140_3Compliant
                                      ? "green"
                                      : "red"
                                  }
                                >
                                  {selectedAsset.fips140_3Compliant
                                    ? "Compliant"
                                    : "Not Compliant"}
                                </Label>
                              </DescriptionListDescription>
                            </DescriptionListGroup>
                            {selectedAsset.primitive && (
                              <DescriptionListGroup>
                                <DescriptionListTerm>Primitive Type</DescriptionListTerm>
                                <DescriptionListDescription>
                                  {selectedAsset.primitive}
                                </DescriptionListDescription>
                              </DescriptionListGroup>
                            )}
                            {selectedAsset.cryptoFunctions && selectedAsset.cryptoFunctions.length > 0 && (
                              <DescriptionListGroup>
                                <DescriptionListTerm>Crypto Functions</DescriptionListTerm>
                                <DescriptionListDescription>
                                  <div style={{ display: "flex", gap: "4px", flexWrap: "wrap" }}>
                                    {selectedAsset.cryptoFunctions.map((func, index) => (
                                      <Label key={index} color="blue">
                                        {func}
                                      </Label>
                                    ))}
                                  </div>
                                </DescriptionListDescription>
                              </DescriptionListGroup>
                            )}
                          </DescriptionList>
                        </CardBody>
                      </Card>
                    </StackItem>
                    {selectedAsset.sboms && selectedAsset.sboms.length > 0 && (
                      <StackItem>
                        <Card>
                          <CardBody>
                            <Title headingLevel="h3" size="lg">
                              Associated SBOMs
                            </Title>
                            <Content style={{ marginTop: "1rem", marginBottom: "1rem" }}>
                              This cryptographic asset is used in {selectedAsset.sboms.length} SBOM
                              {selectedAsset.sboms.length !== 1 ? "s" : ""}:
                            </Content>
                            <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
                              {selectedAsset.sboms.map((sbom) => (
                                <Link
                                  key={sbom.id}
                                  to={Paths.sbomDetails.replace(":sbomId", sbom.id)}
                                  style={{
                                    padding: "var(--pf-v6-global--spacer--sm)",
                                    backgroundColor: "var(--pf-v6-global--BackgroundColor--100)",
                                    border: "1px solid var(--pf-v6-global--BorderColor--100)",
                                    borderRadius: "4px",
                                    textDecoration: "none",
                                    color: "var(--pf-v6-global--link--Color)",
                                    display: "block",
                                  }}
                                  onMouseEnter={(e) => {
                                    e.currentTarget.style.backgroundColor = "var(--pf-v6-global--BackgroundColor--150)";
                                  }}
                                  onMouseLeave={(e) => {
                                    e.currentTarget.style.backgroundColor = "var(--pf-v6-global--BackgroundColor--100)";
                                  }}
                                >
                                  <Content>
                                    <strong>{sbom.name}</strong>
                                  </Content>
                                </Link>
                              ))}
                            </div>
                          </CardBody>
                        </Card>
                      </StackItem>
                    )}
                    {selectedAsset.occurrences && selectedAsset.occurrences.length > 0 && (
                      <StackItem>
                        <Card>
                          <CardBody>
                            <Title headingLevel="h3" size="lg">
                              Code Occurrences
                            </Title>
                            <Content style={{ marginTop: "1rem", marginBottom: "1rem" }}>
                              Found {selectedAsset.occurrences.length} occurrence
                              {selectedAsset.occurrences.length !== 1 ? "s" : ""} in source code:
                            </Content>
                            <div style={{ maxHeight: "300px", overflowY: "auto" }}>
                              {selectedAsset.occurrences.map((occurrence, index) => (
                                <div
                                  key={index}
                                  style={{
                                    padding: "var(--pf-v6-global--spacer--sm)",
                                    marginBottom: "var(--pf-v6-global--spacer--xs)",
                                    backgroundColor: "var(--pf-v6-global--BackgroundColor--100)",
                                    borderLeft: "3px solid var(--pf-v6-global--primary-color--100)",
                                    borderRadius: "4px",
                                  }}
                                >
                                  <Content>
                                    <strong>{occurrence.location}</strong>
                                    {occurrence.line && (
                                      <span style={{ marginLeft: "0.5rem", color: "var(--pf-v6-global--Color--200)" }}>
                                        (line {occurrence.line})
                                      </span>
                                    )}
                                  </Content>
                                  {occurrence.context && (
                                    <Content style={{ marginTop: "0.25rem", fontFamily: "monospace", fontSize: "0.875rem" }}>
                                      {occurrence.context}
                                    </Content>
                                  )}
                                </div>
                              ))}
                            </div>
                          </CardBody>
                        </Card>
                      </StackItem>
                    )}
                    {selectedAsset.libraryCapabilities && selectedAsset.libraryCapabilities.length > 0 && (
                      <StackItem>
                        <Card>
                          <CardBody>
                            <Title headingLevel="h3" size="md">
                              {selectedAsset.libraryName} v{selectedAsset.libraryVersion} Support
                            </Title>
                            <div style={{ marginTop: "1rem", display: "flex", flexDirection: "column", gap: "0.75rem" }}>
                              {selectedAsset.detectedUsage && selectedAsset.detectedUsage.length > 0 && (
                                <div>
                                  <Content style={{ fontSize: "0.875rem", fontWeight: "bold", marginBottom: "0.5rem" }}>
                                    Detected in code:
                                  </Content>
                                  <div style={{ display: "flex", gap: "4px", flexWrap: "wrap" }}>
                                    {selectedAsset.detectedUsage.map((usage, index) => (
                                      <Label key={index} color="red">
                                        {usage}
                                      </Label>
                                    ))}
                                  </div>
                                </div>
                              )}
                              {selectedAsset.libraryCapabilities.filter((cap) => !selectedAsset.detectedUsage?.includes(cap)).length > 0 && (
                                <div>
                                  <Content style={{ fontSize: "0.875rem", fontWeight: "bold", marginBottom: "0.5rem" }}>
                                    Available but not used:
                                  </Content>
                                  <div style={{ display: "flex", gap: "4px", flexWrap: "wrap" }}>
                                    {selectedAsset.libraryCapabilities
                                      .filter((cap) => !selectedAsset.detectedUsage?.includes(cap))
                                      .map((capability, index) => (
                                        <Label key={index} color="orange">
                                          {capability}
                                        </Label>
                                      ))}
                                  </div>
                                </div>
                              )}
                            </div>
                          </CardBody>
                        </Card>
                      </StackItem>
                    )}
                  </Stack>
                ) : (
                  <Content>Select an asset from the table to view details.</Content>
                )}
              </DrawerPanelBody>
            </DrawerPanelContent>
          }
        >
          <DrawerContentBody>
            <PageSection>
              <Table aria-label="Cryptographic assets table" variant="compact">
                <Thead>
                  <Tr>
                    {columns.map((column) => (
                      <Th key={column}>{column}</Th>
                    ))}
                  </Tr>
                </Thead>
                <Tbody>
                  {filteredAssets.map((asset) => (
                    <Tr
                      key={asset.id}
                      onClick={() => handleRowClick(asset)}
                      style={{ cursor: "pointer" }}
                      isHoverable
                    >
                      <Td dataLabel={columns[0]}>
                        <div style={{ display: "flex", flexDirection: "column", gap: "0.25rem" }}>
                          <Content>
                            <span
                              style={{
                                color: "#0066cc",
                                cursor: "pointer",
                                textDecoration: "underline",
                              }}
                            >
                              {asset.algorithm}
                            </span>
                          </Content>
                          {asset.keyStrength && (
                            <Content>
                              <small>{asset.keyStrength} bits</small>
                            </Content>
                          )}
                        </div>
                      </Td>
                      <Td dataLabel={columns[1]}>
                        <div style={{ display: "flex", flexDirection: "column", gap: "0.25rem" }}>
                          <Content>
                            {asset.libraryName}
                          </Content>
                          {asset.libraryVersion && (
                            <Content>
                              <small>v{asset.libraryVersion}</small>
                            </Content>
                          )}
                        </div>
                      </Td>
                      <Td dataLabel={columns[2]}>
                        <Label color={getTypeColor(asset.type)}>
                          {asset.type}
                        </Label>
                      </Td>
                      <Td dataLabel={columns[3]}>
                        <Label color={getRiskColor(asset.risk)}>
                          {asset.risk}
                        </Label>
                      </Td>
                      <Td dataLabel={columns[4]}>
                        {asset.sboms && asset.sboms.length > 0 ? (
                          <Link
                            to={getSbomFilteredByAlgorithmUrl([asset.algorithm])}
                            style={{
                              color: "#0066cc",
                            }}
                          >
                            {asset.sboms.length} SBOM{asset.sboms.length !== 1 ? "s" : ""}
                          </Link>
                        ) : (
                          "0 SBOMs"
                        )}
                      </Td>
                    </Tr>
                  ))}
                </Tbody>
              </Table>
            </PageSection>
          </DrawerContentBody>
        </DrawerContent>
      </Drawer>
    </>
  );
};
